# Aarvion governance packs — generated by internal/packs.EmitRego.
#
# Full-strength CP policy for beta.aarvion.ai: denies/asks equivalently to the
# local overlay but may deny outright. Evaluated at data.envoy.authz.allow for
# every governed OpenClaw tool call. Pack modes live in data.packs so the same
# module retunes from data.json alone. DO NOT EDIT BY HAND — regenerate via
# `go test ./internal/packs/ -run Snapshot -update`.
package envoy.authz

import rego.v1

default allow := {"allowed": true, "http_status": 200}

# --- semantic action + caller (from the guard normalizer) ---
surface := lower(object.get(input, ["action", "semantic", "surface"], ""))
verb := lower(object.get(input, ["action", "semantic", "verb"], ""))
command := lower(object.get(input, ["action", "semantic", "raw"], ""))
host := lower(object.get(input, ["action", "semantic", "host"], ""))
findings := object.get(input, ["action", "semantic", "findings"], [])
flags := object.get(input, ["action", "semantic", "flags"], {})
targets := object.get(input, ["action", "semantic", "targets"], [])
principal := lower(object.get(input, ["ctx", "caller", "principal_id"], ""))

# in_window reports whether minute-of-day m falls in a wraparound quiet-hours
# window that crosses midnight (end <= start), e.g. 23:00-07:00.
in_window(m, start, end) if m >= start
in_window(m, start, end) if m < end

# --- pack modes (from data.packs) ---
mode_api_guard := object.get(data.packs, ["api-guard", "mode"], "off")
mode_comms_guard := object.get(data.packs, ["comms-guard", "mode"], "off")
mode_dlp_guard := object.get(data.packs, ["dlp-guard", "mode"], "off")
mode_github_guard := object.get(data.packs, ["github-guard", "mode"], "off")
mode_google_guard := object.get(data.packs, ["google-guard", "mode"], "off")
mode_infra_guard := object.get(data.packs, ["infra-guard", "mode"], "off")
mode_social_guard := object.get(data.packs, ["social-guard", "mode"], "off")

violations contains v if {
	mode_api_guard == "enforce"
	surface == "api"
	count([fl | some fl in {"delete_verb", "destructive"}; object.get(flags, fl, false) == true]) > 0
	v := {"id": "govern.api.destructive.v1", "text": "api destructive"}
}

violations contains v if {
	mode_dlp_guard == "enforce"
	some f in findings
	startswith(lower(f), "secret:")
	v := {"id": "govern.dlp.secret.v1", "text": "dlp secret"}
}

violations contains v if {
	mode_github_guard == "enforce"
	surface == "github"
	verb == "force_push"
	v := {"id": "govern.github.force_push.v1", "text": "github force push"}
}

violations contains v if {
	mode_github_guard == "enforce"
	surface == "github"
	verb == "repo_delete"
	v := {"id": "govern.github.repo_delete.v1", "text": "github repo delete"}
}

violations contains v if {
	mode_github_guard == "enforce"
	surface == "github"
	verb == "secret_set"
	v := {"id": "govern.github.secret_set.v1", "text": "github secret set"}
}

violations contains v if {
	mode_google_guard == "enforce"
	surface in {"file", "doc", "sheet", "drive"}
	verb == "delete"
	v := {"id": "govern.google.drive_delete.v1", "text": "google drive delete"}
}

violations contains v if {
	mode_google_guard == "enforce"
	surface in {"file", "doc", "sheet", "drive"}
	verb == "share"
	object.get(flags, "public_share", false) == true
	v := {"id": "govern.google.public_share.v1", "text": "google public share"}
}

violations contains v if {
	mode_infra_guard == "enforce"
	contains(command, "docker rm -f")
	v := {"id": "govern.infra.dangerous_0.v1", "text": "infra dangerous 0"}
}

violations contains v if {
	mode_infra_guard == "enforce"
	contains(command, "docker system prune")
	v := {"id": "govern.infra.dangerous_1.v1", "text": "infra dangerous 1"}
}

violations contains v if {
	mode_infra_guard == "enforce"
	contains(command, "docker volume rm")
	v := {"id": "govern.infra.dangerous_2.v1", "text": "infra dangerous 2"}
}

violations contains v if {
	mode_infra_guard == "enforce"
	contains(command, "systemctl stop")
	v := {"id": "govern.infra.dangerous_3.v1", "text": "infra dangerous 3"}
}

violations contains v if {
	mode_infra_guard == "enforce"
	contains(command, "systemctl disable")
	v := {"id": "govern.infra.dangerous_4.v1", "text": "infra dangerous 4"}
}

violations contains v if {
	mode_infra_guard == "enforce"
	contains(command, "launchctl unload")
	v := {"id": "govern.infra.dangerous_5.v1", "text": "infra dangerous 5"}
}

violations contains v if {
	mode_infra_guard == "enforce"
	contains(command, "kill -9 1")
	v := {"id": "govern.infra.dangerous_6.v1", "text": "infra dangerous 6"}
}

violations contains v if {
	mode_infra_guard == "enforce"
	contains(command, "shutdown")
	v := {"id": "govern.infra.dangerous_7.v1", "text": "infra dangerous 7"}
}

violations contains v if {
	mode_infra_guard == "enforce"
	contains(command, "reboot")
	v := {"id": "govern.infra.dangerous_8.v1", "text": "infra dangerous 8"}
}

violations contains v if {
	mode_infra_guard == "enforce"
	contains(command, "halt")
	v := {"id": "govern.infra.dangerous_9.v1", "text": "infra dangerous 9"}
}

violations contains v if {
	mode_infra_guard == "enforce"
	surface == "infra"
	object.get(flags, "destructive", false) == true
	v := {"id": "govern.infra.destructive.v1", "text": "infra destructive"}
}

violations contains v if {
	mode_social_guard == "enforce"
	surface == "twitter"
	verb in {"post", "reply", "dm", "follow", "like"}
	v := {"id": "govern.social.write.v1", "text": "social write"}
}

ask_reasons contains r if {
	mode_api_guard == "ask"
	surface == "api"
	count([fl | some fl in {"delete_verb", "destructive"}; object.get(flags, fl, false) == true]) > 0
	r := "api destructive"
}

ask_reasons contains r if {
	mode_comms_guard in {"enforce", "ask"}
	surface == "comms"
	verb in {"send", "post", "dm", "reply"}
	now_min := object.get(input, ["action", "semantic", "now_minute"], -1)
	now_min >= 0
	in_window(now_min, 1380, 420)
	r := "comms quiet hours"
}

ask_reasons contains r if {
	mode_dlp_guard in {"enforce", "ask"}
	some f in findings
	startswith(lower(f), "pii:")
	r := "dlp pii"
}

ask_reasons contains r if {
	mode_dlp_guard == "ask"
	some f in findings
	startswith(lower(f), "secret:")
	r := "dlp secret"
}

ask_reasons contains r if {
	mode_github_guard == "ask"
	surface == "github"
	verb == "force_push"
	r := "github force push"
}

ask_reasons contains r if {
	mode_github_guard in {"enforce", "ask"}
	surface == "github"
	verb == "push"
	r := "github push"
}

ask_reasons contains r if {
	mode_github_guard == "ask"
	surface == "github"
	verb == "repo_delete"
	r := "github repo delete"
}

ask_reasons contains r if {
	mode_github_guard == "ask"
	surface == "github"
	verb == "secret_set"
	r := "github secret set"
}

ask_reasons contains r if {
	mode_github_guard in {"enforce", "ask"}
	contains(command, ".github/workflows")
	r := "github workflow edit"
}

ask_reasons contains r if {
	mode_google_guard == "ask"
	surface in {"file", "doc", "sheet", "drive"}
	verb == "delete"
	r := "google drive delete"
}

ask_reasons contains r if {
	mode_google_guard in {"enforce", "ask"}
	surface == "email"
	verb == "send"
	r := "google email send"
}

ask_reasons contains r if {
	mode_google_guard == "ask"
	surface in {"file", "doc", "sheet", "drive"}
	verb == "share"
	object.get(flags, "public_share", false) == true
	r := "google public share"
}

ask_reasons contains r if {
	mode_infra_guard == "ask"
	contains(command, "docker rm -f")
	r := "infra dangerous 0"
}

ask_reasons contains r if {
	mode_infra_guard == "ask"
	contains(command, "docker system prune")
	r := "infra dangerous 1"
}

ask_reasons contains r if {
	mode_infra_guard == "ask"
	contains(command, "docker volume rm")
	r := "infra dangerous 2"
}

ask_reasons contains r if {
	mode_infra_guard == "ask"
	contains(command, "systemctl stop")
	r := "infra dangerous 3"
}

ask_reasons contains r if {
	mode_infra_guard == "ask"
	contains(command, "systemctl disable")
	r := "infra dangerous 4"
}

ask_reasons contains r if {
	mode_infra_guard == "ask"
	contains(command, "launchctl unload")
	r := "infra dangerous 5"
}

ask_reasons contains r if {
	mode_infra_guard == "ask"
	contains(command, "kill -9 1")
	r := "infra dangerous 6"
}

ask_reasons contains r if {
	mode_infra_guard == "ask"
	contains(command, "shutdown")
	r := "infra dangerous 7"
}

ask_reasons contains r if {
	mode_infra_guard == "ask"
	contains(command, "reboot")
	r := "infra dangerous 8"
}

ask_reasons contains r if {
	mode_infra_guard == "ask"
	contains(command, "halt")
	r := "infra dangerous 9"
}

ask_reasons contains r if {
	mode_infra_guard == "ask"
	surface == "infra"
	object.get(flags, "destructive", false) == true
	r := "infra destructive"
}

ask_reasons contains r if {
	mode_social_guard == "ask"
	surface == "twitter"
	verb in {"post", "reply", "dm", "follow", "like"}
	r := "social write"
}

# --- decision: deny (hard) > ask (approval) > allow (default) ---

allow := decision if {
	count(violations) > 0
	ids := sort([v.id | some v in violations])
	texts := sort([v.text | some v in violations])
	decision := {
		"allowed": false,
		"http_status": 403,
		"headers": {
			"x-policy-violated": concat(",", ids),
			"x-policy-reason": sprintf("blocked: %s", [concat("; ", texts)]),
		},
	}
}

allow := decision if {
	count(violations) == 0
	count(ask_reasons) > 0
	decision := {
		"allowed": false,
		"http_status": 202,
		"headers": {
			"x-aarvion-verdict": "ask",
			"x-policy-violated": "govern.ask.approval_required.v1",
			"x-policy-reason": sprintf("approval required: %s", [concat("; ", sort(ask_reasons))]),
		},
	}
}
